[haproxy]
prs-rvp-01 ansible_host=10.10.10.10 dmz_ip=10.9.175.10 mgmt_ip=10.9.99.110 keepalived_state=MASTER keepalived_priority=110
prs-rvp-02 ansible_host=10.10.10.11 dmz_ip=10.9.175.11 mgmt_ip=10.9.99.111 keepalived_state=BACKUP keepalived_priority=100

[web]
prs-web-01 ansible_host=10.10.10.20 dmz_ip=10.9.175.20 mgmt_ip=10.9.99.120
prs-web-02 ansible_host=10.10.10.21 dmz_ip=10.9.175.21 mgmt_ip=10.9.99.121
prs-web-03 ansible_host=10.10.10.22 dmz_ip=10.9.175.22 mgmt_ip=10.9.99.122

[routeur]
prs-tsr-01 ansible_host=10.10.10.1

[dmz:children]
haproxy
web

[linux:children]
dmz
routeur

[linux:vars]
ansible_user=ansible
